const users = [
  {
    id: "1",
    name: "John Doe",
    age: 25,
    gender: "male",
    interests: ["hiking", "cooking", "movies"],
    location: "Nairobi",
    bio: "I love exploring new places and trying different cuisines.",
    photos: [
      "https://images.pexels.com/photos/2853592/pexels-photo-2853592.jpeg?auto=compress&cs=tinysrgb&w=400",
    ],
    height: 180,
    education: "Bachelor's Degree",
    job: "Software Engineer",
    ethnicity: "Caucasian",
    religion: "Agnostic",
    bodyType: "Athletic",
    hobbies: ["Guitar", "Reading", "Traveling"],
    music: ["Pop", "Rock", "Hip Hop"],
    books: ["Fiction", "Self-help"],
    relationships: "Single",
    lookingFor: {
      ageRange: "22-30",
      gender: "female",
      location: "Any",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "2",
    name: "Jane Smith",
    age: 28,
    gender: "female",
    interests: ["yoga", "reading", "traveling"],
    location: "Mombasa",
    bio: "Passionate about yoga and exploring new destinations.",
    photos: [
      "https://example.com/photo3.jpg",
      "https://example.com/photo4.jpg",
    ],
    height: 165,
    education: "Master's Degree",
    job: "Marketing Manager",
    ethnicity: "African",
    religion: "Christian",
    bodyType: "Slim",
    hobbies: ["Painting", "Hiking", "Photography"],
    music: ["R&B", "Jazz", "Reggae"],
    books: ["Biographies", "Mystery"],
    relationships: "Single",
    lookingFor: {
      ageRange: "25-35",
      gender: "male",
      location: "Nairobi",
      occupation: "Any",
      diet: "Vegetarian",
    },
  },
  {
    id: "3",
    name: "David Wangari",
    age: 30,
    gender: "male",
    interests: ["sports", "music", "traveling"],
    location: "Nairobi",
    bio: "Passionate about sports and exploring different cultures.",
    photos: [
      "https://example.com/photo5.jpg",
      "https://example.com/photo6.jpg",
    ],
    height: 175,
    education: "Bachelor's Degree",
    job: "Financial Analyst",
    ethnicity: "African",
    religion: "Christian",
    bodyType: "Average",
    hobbies: ["Football", "Playing guitar", "Cooking"],
    music: ["Hip Hop", "Reggae", "Pop"],
    books: ["Biographies", "Business"],
    relationships: "Single",
    lookingFor: {
      ageRange: "25-35",
      gender: "female",
      location: "Nairobi",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "4",
    name: "Emily Johnson",
    age: 24,
    gender: "female",
    interests: ["reading", "painting", "music"],
    location: "Mombasa",
    bio: "An artist who loves reading and listening to music.",
    photos: [
      "https://example.com/photo7.jpg",
      "https://example.com/photo8.jpg",
    ],
    height: 160,
    education: "Bachelor's Degree",
    job: "Graphic Designer",
    ethnicity: "Caucasian",
    religion: "Agnostic",
    bodyType: "Slim",
    hobbies: ["Drawing", "Writing", "Dancing"],
    music: ["Indie", "Alternative", "Electronic"],
    books: ["Fantasy", "Art"],
    relationships: "Single",
    lookingFor: {
      ageRange: "22-30",
      gender: "male",
      location: "Mombasa",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "5",
    name: "Michael Kimani",
    age: 32,
    gender: "male",
    interests: ["photography", "traveling", "music"],
    location: "Nairobi",
    bio: "Photographer who loves capturing moments and exploring the world.",
    photos: [
      "https://example.com/photo9.jpg",
      "https://example.com/photo10.jpg",
    ],
    height: 185,
    education: "Bachelor's Degree",
    job: "Photographer",
    ethnicity: "African",
    religion: "Agnostic",
    bodyType: "Athletic",
    hobbies: ["Gaming", "Reading", "Cooking"],
    music: ["Rock", "Pop", "Hip Hop"],
    books: ["Non-fiction", "Biographies"],
    relationships: "Single",
    lookingFor: {
      ageRange: "25-35",
      gender: "female",
      location: "Any",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "6",
    name: "Sara Ahmed",
    age: 27,
    gender: "female",
    interests: ["yoga", "cooking", "movies"],
    location: "Nairobi",
    bio: "Passionate about yoga and trying out new recipes.",
    photos: [
      "https://example.com/photo11.jpg",
      "https://example.com/photo12.jpg",
    ],
    height: 170,
    education: "Bachelor's Degree",
    job: "Teacher",
    ethnicity: "Asian",
    religion: "Muslim",
    bodyType: "Average",
    hobbies: ["Traveling", "Photography", "Painting"],
    music: ["Pop", "R&B", "Classical"],
    books: ["Self-help", "Mystery"],
    relationships: "Single",
    lookingFor: {
      ageRange: "25-35",
      gender: "male",
      location: "Any",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "7",
    name: "Daniel Mwangi",
    age: 29,
    gender: "male",
    interests: ["sports", "reading", "music"],
    location: "Nairobi",
    bio: "Sports enthusiast who enjoys reading and listening to music.",
    photos: [
      "https://example.com/photo13.jpg",
      "https://example.com/photo14.jpg",
    ],
    height: 175,
    education: "Master's Degree",
    job: "Architect",
    ethnicity: "African",
    religion: "Christian",
    bodyType: "Athletic",
    hobbies: ["Football", "Writing", "Playing guitar"],
    music: ["Rock", "Pop", "Reggae"],
    books: ["Science fiction", "History"],
    relationships: "Single",
    lookingFor: {
      ageRange: "25-35",
      gender: "female",
      location: "Nairobi",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "8",
    name: "Linda Okoth",
    age: 26,
    gender: "female",
    interests: ["painting", "traveling", "music"],
    location: "Mombasa",
    bio: "An artist who loves exploring new destinations and creating art.",
    photos: [
      "https://example.com/photo15.jpg",
      "https://example.com/photo16.jpg",
    ],
    height: 163,
    education: "Bachelor's Degree",
    job: "Freelancer",
    ethnicity: "African",
    religion: "Christian",
    bodyType: "Slim",
    hobbies: ["Reading", "Writing", "Dancing"],
    music: ["Indie", "Alternative", "Pop"],
    books: ["Art", "Poetry"],
    relationships: "Single",
    lookingFor: {
      ageRange: "22-30",
      gender: "male",
      location: "Mombasa",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "9",
    name: "James Kimani",
    age: 31,
    gender: "male",
    interests: ["photography", "traveling", "movies"],
    location: "Nairobi",
    bio: "Passionate about photography and exploring new movies.",
    photos: [
      "https://example.com/photo17.jpg",
      "https://example.com/photo18.jpg",
    ],
    height: 180,
    education: "Bachelor's Degree",
    job: "Marketing Executive",
    ethnicity: "African",
    religion: "Christian",
    bodyType: "Average",
    hobbies: ["Gaming", "Reading", "Cooking"],
    music: ["Rock", "Hip Hop", "Pop"],
    books: ["Non-fiction", "Business"],
    relationships: "Single",
    lookingFor: {
      ageRange: "25-35",
      gender: "female",
      location: "Any",
      occupation: "Any",
      diet: "No preference",
    },
  },
  {
    id: "10",
    name: "Julia Njeri",
    age: 25,
    gender: "female",
    interests: ["hiking", "cooking", "movies"],
    location: "Nairobi",
    bio: "Adventurous spirit who loves cooking and watching movies.",
    photos: [
      "https://example.com/photo19.jpg",
      "https://example.com/photo20.jpg",
    ],
    height: 168,
    education: "Bachelor's Degree",
    job: "Software Engineer",
    ethnicity: "African",
    religion: "Christian",
    bodyType: "Average",
    hobbies: ["Photography", "Reading", "Traveling"],
    music: ["Pop", "Rock", "Hip Hop"],
    books: ["Fiction", "Self-help"],
    relationships: "Single",
    lookingFor: {
      ageRange: "22-30",
      gender: "male",
      location: "Any",
      occupation: "Any",
      diet: "No preference",
    },
  },
];

export default users;
